[
{ name = "ovs-ledger", repo = "https://github.com/icdevsorg/ovs-ledger", version = "v0.0.1", dependencies = ["base", "ic-certification", "icrc1-mo", "icrc2-mo", "icrc3-mo", "icrc4-mo", "icrc75-mo", "stable-write-only", "sha2", "candy", "StableHeapBTreeMap", "principal-ext", "timer-tool"] : List Text },
{ name = "nm", repo = "https://github.com/dr-montasir/nm", version = "v.1.1.0", dependencies = [] : List Text },
{ name = "time", repo = "https://github.com/ArielRobotti/time", version = "2918224d2cb8f73d113ae3380f5f575156f9357c", dependencies = ["base"] : List Text },
{ name = "tweetnacl", repo = "https://github.com/nirvana369/tweetnacl/", version = "v1.1.1", dependencies = ["base"] : List Text },
{ name = "xtended-numbers", repo = "https://github.com/edjCase/motoko_numbers", version = "0a036877112d5f0cbb6903678d43abb6574c617e", dependencies = ["base"] : List Text },
{ name = "jwt", repo = "https://github.com/edjcase/motoko_jwt", version = "0130a82978bedc62617a622e1044071b69a39b09", dependencies = ["base", "new-base", "json", "base-x-encoder", "hmac", "ecdsa", "sha2", "rsa", "eddsa"] : List Text },
{ name = "concurrent", repo = "https://github.com/vporton/ic-concurrent", version = "v0.1.2", dependencies = ["base"] : List Text },
{ name = "icrc-fungible", repo = "https://github.com/PanIndustrial-Org/ICRC_fungible", version = "v0.0.5", dependencies = ["base", "ic-certification", "icrc1-mo", "icrc2-mo", "icrc3-mo", "icrc4-mo"] : List Text },
{ name = "test", repo = "https://github.com/ZenVoich/test", version = "e87a718eba50c0c5d2bd8b52320ed3c51f67e2cf", dependencies = ["base"] : List Text },
{ name = "math", repo = "https://github.com/ArielRobotti/math", version = "7cafbe9b858d31062e4ff6a1d5ca7977be6388ec", dependencies = ["base"] : List Text },
{ name = "ecdsa", repo = "https://github.com/edjCase/motoko_ecdsa", version = "f1cfc1edb3a51ce97459ff764441aa33ba952e20", dependencies = ["sha2", "asn1", "xtended-numbers", "base-x-encoder"] : List Text },
{ name = "assets", repo = "https://github.com/krpeacock/assets", version = "b3b5788a136695cea1b3877f5356f3b8bc205d14", dependencies = ["test"] : List Text },
{ name = "server", repo = "https://github.com/krpeacock/server", version = "v1.0.0", dependencies = ["certified-cache", "test", "base", "assets", "http-parser", "serde"] : List Text },
{ name = "certified-cache", repo = "https://github.com/krpeacock/certified-cache", version = "96ef8a3f05669641506fb90faf01ac55dde9721d", dependencies = ["base", "ic-certification", "StableHashMap", "sha2"] : List Text },
{ name = "glob", repo = "https://github.com/edjcase/motoko_glob", version = "b1d90e0e981820be0bc283f10b9518656322cd44", dependencies = ["base"] : List Text },
{ name = "random", repo = "https://github.com/ArielRobotti/random", version = "Fix", dependencies = [] : List Text },
{ name = "tecdsa", repo = "https://github.com/bittoko/tecdsa", version = "v0.0.4", dependencies = ["test", "sha2", "base", "utilities", "stable-buffer"] : List Text },
{ name = "account", repo = "https://github.com/letmejustputthishere/account", version = "a718d61a8a4086ce13056681567535f975ac0ddf", dependencies = ["array", "base", "itertools"] : List Text },
{ name = "liminal", repo = "https://github.com/edjcase/liminal", version = "v0.0.1", dependencies = ["new-base", "itertools", "xtended-text", "xtended-numbers", "certified-assets", "http-assets", "asn1", "json", "jwt", "compression", "serde", "xml"] : List Text },
{ name = "icrc4-mo", repo = "https://github.com/PanIndustrial-Org/icrc4.mo", version = "v0.0.5", dependencies = ["base", "array", "StableTrieMap", "StableBuffer", "map", "itertools", "vector", "star", "rep-indy-hash", "account", "icrc1-mo"] : List Text },
{ name = "xrc-types", repo = "https://github.com/ZenVoich/xrc-types", version = "aabaee6f2d2b070fbe081f895a4491875f34bac8", dependencies = [] : List Text },
{ name = "make-rules", repo = "https://github.com/vporton/icp-make-rules", version = "v0.0.3", dependencies = [] : List Text },
{ name = "stable-enum", repo = "https://github.com/bittoko/stable-enum", version = "v1.0.0", dependencies = ["base", "stable-buffer"] : List Text },
{ name = "random-class", repo = "https://github.com/ArielRobotti/RandomClass", version = "de45e5844206f1e17d34ee1ebb90fcc4b43fe3fd", dependencies = ["base"] : List Text },
{ name = "base-x-encoder", repo = "https://github.com/edjcase/motoko_base_x", version = "47e9ac57b04f0b9918c4446b88cdc93e1c5aeccf", dependencies = ["new-base", "base"] : List Text },
{ name = "fuzz", repo = "https://github.com/ZenVoich/fuzz", version = "23952c2e69a7c6470a7249133c3632dc58cd8ce7", dependencies = ["base"] : List Text },
{ name = "prng", repo = "https://github.com/research-ag/prng", version = "e003702521d688f1149c2ffdb3e440b6c201dd8b", dependencies = ["base"] : List Text },
{ name = "hash", repo = "https://github.com/aviate-labs/hash.mo", version = "overridden", dependencies = ["base", "array"] : List Text },
{ name = "sha2", repo = "https://github.com/research-ag/sha2", version = "3e14010cc9d23df409452e4776f5b8a29652441b", dependencies = ["base"] : List Text },
{ name = "serde", repo = "https://github.com/NatLabs/serde", version = "ddeb5cf7b14283f12b576d9d3da77e5218602aec", dependencies = ["base", "itertools", "candid", "xtended-numbers", "json-float", "parser-combinators", "cbor", "map", "sha2"] : List Text },
{ name = "neuro", repo = "https://github.com/jesssekeogh/neuro", version = "v0.7.5", dependencies = ["sha2", "encoding", "account-identifier"] : List Text },
{ name = "bench", repo = "https://github.com/ZenVoich/bench", version = "d4ce879cf251a27fa7167b523eee622baca42a53", dependencies = ["base"] : List Text },
{ name = "icrc1", repo = "https://github.com/NatLabs/icrc1", version = "0800c7ac03026a4c5a72eeb357cbbd0aca2f0fb4", dependencies = ["base", "array", "StableTrieMap", "StableBuffer", "itertools"] : List Text },
{ name = "csprng", repo = "https://github.com/temokoki/IC_CSPRNG", version = "3ae7cdc1a1ecb6c78a335ba49aea1b09e3371bfb", dependencies = ["base"] : List Text },
{ name = "stream", repo = "https://github.com/research-ag/stream", version = "141bec30d1f78d2a31dac81c66306c399727c3db", dependencies = ["base", "swb", "vector", "promtracker"] : List Text },
{ name = "icrc-84", repo = "https://github.com/research-ag/icrc-84", version = "0.1.0", dependencies = ["base"] : List Text },
{ name = "icrc1-mo", repo = "https://github.com/PanIndustrial-Org/icrc1.mo", version = "v0.0.15", dependencies = ["base", "array", "StableTrieMap", "StableBuffer", "map", "itertools", "vector", "star", "rep-indy-hash", "account"] : List Text },
{ name = "lrucache", repo = "https://github.com/Demali-876/lru-cache", version = "e4021f823d3a9ce54ea6a992d51ab8239a3f52a2", dependencies = ["base"] : List Text },
{ name = "icrc2-mo", repo = "https://github.com/PanIndustrial-Org/icrc2.mo", version = "v0.0.13", dependencies = ["base", "array", "StableTrieMap", "StableBuffer", "map", "itertools", "vector", "star", "rep-indy-hash", "account", "icrc1-mo"] : List Text },
{ name = "new-candb", repo = "https://github.com/ORIGYN-SA/CanDB/tree/main", version = "v1.0.0", dependencies = ["base", "StableHashMap", "stable-rbtree", "stable-buffer", "json", "crypto", "array", "encoding"] : List Text },
{ name = "bitbuffer", repo = "https://github.com/NatLabs/BitBuffer", version = "5622d4d7572ca9da87b0448f0b9d0e407df9d2e4", dependencies = ["base", "buffer-deque"] : List Text },
{ name = "icrc2-types", repo = "https://github.com/ZenVoich/icrc2-types", version = "808ead8a7b9d6e6e8f966038db5ca7e5a9601e03", dependencies = [] : List Text },
{ name = "icrc1-types", repo = "https://github.com/ZenVoich/icrc1-types", version = "effd430c62a99e5ab68d17dd5fcdaec30c0c5adc", dependencies = [] : List Text },
{ name = "http-assets", repo = "https://github.com/edjcase/ic-assets", version = "v0.0.6", dependencies = ["base", "http-types", "map", "certified-assets", "ic", "itertools", "vector", "encoding", "http-parser", "sha2", "memory-region"] : List Text },
{ name = "time-consts", repo = "https://github.com/ZenVoich/time-consts", version = "360295b4c1b969332c07aed299df2ce416ec844f", dependencies = [] : List Text },
{ name = "icrc2-batch", repo = "https://github.com/MemeFighterCo/icrc2-batch", version = "v1.0.1", dependencies = ["testing", "base"] : List Text },
{ name = "promtracker", repo = "https://github.com/research-ag/promtracker", version = "0.5.4", dependencies = ["base", "vector"] : List Text },
{ name = "buffer-deque", repo = "https://github.com/NatLabs/BufferDeque", version = "2ebdc1200a7c932e076f042695c1a976f0f5638b", dependencies = ["base"] : List Text },
{ name = "ledger-types", repo = "https://github.com/ZenVoich/ledger-types", version = "40a14199e72286ba4db86b01c669f51d7469de2d", dependencies = [] : List Text },
{ name = "token-handler", repo = "https://github.com/research-ag/token-handler", version = "439010ace0769aded1a7118fa3e82bd32dcb6ca2", dependencies = ["base", "icrc-84"] : List Text },
{ name = "memory-buffer", repo = "https://github.com/NatLabs/memory-buffer", version = "a98abe76b54272a4aeba8e133d78161f5399ca47", dependencies = ["base", "itertools", "memory-region"] : List Text },
{ name = "nacdb-reorder", repo = "https://github.com/vporton/nacdb-reorder", version = "v3.2.1", dependencies = ["base", "nacdb", "StableBuffer", "map", "StableHeapBTreeMap", "itertools", "xtended-numbers"] : List Text },
{ name = "stable-buffer", repo = "https://github.com/bittoko/stable-buffer", version = "v1.0.1", dependencies = ["base", "test"] : List Text },
{ name = "memory-region", repo = "https://github.com/NatLabs/memory-region", version = "c8d5e0c4ed4f9b106d0ed2fdf82f01b3273e8eb0", dependencies = ["base", "itertools", "StableHeapBTreeMap", "map", "augmented-btrees"] : List Text },
{ name = "ckbtc-address", repo = "https://github.com/research-ag/ckbtc-address", version = "0.0.1", dependencies = ["base", "bitcoin"] : List Text },
{ name = "passport-client", repo = "https://github.com/vporton/passport-client-dfinity", version = "v0.4.9", dependencies = ["base", "sequence", "candb", "candb-multi", "stable-buffer", "StableBuffer", "date.mo", "motoko-sequence", "json.mo"] : List Text },
{ name = "af-role-rotator", repo = "https://github.com/icdevsorg/af-role-rotator", version = "v0.0.1", dependencies = ["base", "map", "vector", "star", "account", "icrc3-mo", "icrc10-mo", "xtended-random", "icrc75-mo", "ic-certification", "timer-tool", "ovs-fixed", "candy", "icrc1-mo", "StableHeapBTreeMap", "icrc104-mo"] : List Text },
{ name = "augmented-btrees", repo = "https://github.com/NatLabs/augmented-btrees", version = "4aa19673ff4bce8588490af743b99670b22e5e36", dependencies = ["base", "buffer-deque", "itertools"] : List Text },
{ name = "memory-hashtable", repo = "https://github.com/fGhost713/memory-HashTable", version = "v1.0.5", dependencies = ["base", "memory-region", "StableTrieMap", "itertools", "test", "memory-buffer"] : List Text },
{ name = "memory-collection", repo = "https://github.com/NatLabs/memory-collection", version = "v0.0.4", dependencies = ["base", "itertools", "memory-region", "buffer-deque", "memory-collection"] : List Text },
{ name = "account-identifier", repo = "https://github.com/letmejustputthishere/account-identifiers", version = "d07f70f572fc0d4cfe44333276c92611de3e0d44", dependencies = ["sha2", "hash"] : List Text },
{ name = "dao-proposal-engine", repo = "https://github.com/edjcase/motoko_proposal_engine", version = "a80694ced5339bac2f67204b6a9b6c58983bab87", dependencies = ["base", "itertools"] : List Text },
{ name = "swb", repo = "https://github.com/research-ag/swb", version = "1.2.0", dependencies = ["base"] : List Text },
{ name = "ekvm", repo = "https://github.com/BarFTW/Ekvm", version = "overridden", dependencies = ["StableHeapBTreeMap", "base"] : List Text },
{ name = "asn1", repo = "https://github.com/edjcase/motoko_asn1", version = "a32d730a36f01c48e86c40d02f6cf226d224a66b", dependencies = ["base", "new-base", "itertools", "xtended-numbers"] : List Text },
{ name = "sha3", repo = "https://github.com/hanbu97/motoko-sha3", version = "v0.1.1", dependencies = ["base", "iterext"] : List Text },
{ name = "json", repo = "https://github.com/Demali-876/json", version = "1402c1bb961e42dc28b583eed7a61823f2fcc954", dependencies = ["xtended-numbers"] : List Text },
{ name = "regex", repo = "https://github.com/Demali-876/motoko_regex_engine", version = "v2.7.1", dependencies = ["base"] : List Text },
{ name = "geecs", repo = "https://github.com/jneums/geecs", version = "2c506fd0dda38db81ec6ab599799d9821bd388db", dependencies = ["base", "StableHashMap", "vector"] : List Text },
{ name = "vector", repo = "https://github.com/research-ag/vector", version = "0.4.1", dependencies = ["base"] : List Text },
{ name = "base64", repo = "https://github.com/nirvana369/base64", version = "v1.0.0", dependencies = ["test", "bench"] : List Text },
{ name = "backup", repo = "https://github.com/ZenVoich/backup", version = "01ba874188744e674b23d81b49b3ca971f26d381", dependencies = ["base", "map", "linked-list", "http-types", "motoko-datetime", "memory-region"] : List Text },
{ name = "deflate", repo = "https://github.com/NatLabs/deflate.mo", version = "385fcb93b089317fb1fb311e726d0c2b627c6fca", dependencies = ["base", "itertools", "circular-buffer", "bitbuffer", "hash", "buffer-deque", "array"] : List Text },
{ name = "rechain", repo = "https://github.com/neutrinomic/rechain", version = "3d3203c0fb44407912868515089516e201495e83", dependencies = ["base", "map", "sha2", "vector", "rep-indy-hash", "stable-write-only", "swbstable", "itertools", "ic-certification", "mosup"] : List Text },
{ name = "datetime", repo = "https://github.com/edjcase/motoko_datetime", version = "178f107b65230c718f6eda4677502e0b02b841ba", dependencies = ["base", "xtended-text"] : List Text },
{ name = "generics", repo = "https://github.com/research-ag/generics", version = "35299790eca2192280da9a0610551759f3d3939b", dependencies = ["base"] : List Text },
{ name = "swbstable", repo = "https://github.com/infu/swb", version = "8f68ed961ac5e4b2d9eed95ff68d33e2a98890b2", dependencies = ["base"] : List Text },
{ name = "utilities", repo = "https://github.com/bittoko/utils", version = "v2.0.2", dependencies = ["test", "xtended-numbers", "base", "map"] : List Text },
{ name = "ic-assets", repo = "https://github.com/NatLabs/ic-assets", version = "v0.1.0", dependencies = ["base", "http-types", "map", "certified-assets", "ic", "itertools", "vector", "encoding", "http-parser", "sha2"] : List Text },
{ name = "date-time", repo = "https://github.com/toshakparmar/date-time-motoko", version = "aa6f3428af02b360e557fc68759d4bf5aa133e6a", dependencies = ["base"] : List Text },
{ name = "async-test", repo = "https://github.com/research-ag/async-test", version = "193f25e9fa223c96361c1da941974ebe3c695a8d", dependencies = ["base"] : List Text },
{ name = "icrc104-mo", repo = "https://github.com/icdevsorg/icrc104.mo", version = "v0.0.1", dependencies = ["base", "vector", "star", "account", "icrc3-mo", "map", "ic-certification", "timer-tool", "ovs-fixed", "candy", "icrc1-mo", "icrc10-mo", "icrc75-mo"] : List Text },
{ name = "http-types", repo = "https://github.com/ZenVoich/http-types", version = "v1.0.1", dependencies = [] : List Text },
{ name = "candb-multi", repo = "https://github.com/vporton/candb-multi", version = "v0.11.8", dependencies = ["candb", "stable-rbtree", "StableBuffer", "base"] : List Text },
{ name = "ordered-map", repo = "https://github.com/vporton/ordered-map.mo", version = "v0.2.2", dependencies = ["base"] : List Text },
{ name = "compression", repo = "https://github.com/edjcase/motoko_compression", version = "85464ea13990574633f396324028be3ffae4802f", dependencies = ["base", "itertools", "circular-buffer", "bitbuffer", "buffer-deque", "test"] : List Text },
{ name = "file-uploader", repo = "https://github.com/ArielRobotti/file-uploader", version = "df41d5b53cc4ff69fb4e5d132ac79a82f3e91d7c", dependencies = ["map"] : List Text },
{ name = "cycles-simple", repo = "https://github.com/vporton/cycles-simple", version = "overridden", dependencies = ["StableHashMap", "base"] : List Text },
{ name = "football-types", repo = "https://github.com/JohnNixon6972/FootballTypes", version = "c02095944568b3113805fdec23bf1dd141e1c01d", dependencies = ["base"] : List Text },
{ name = "circular-buffer", repo = "https://github.com/NatLabs/CircularBuffer", version = "eecd121f4c2347563699266b5a0fb6bff6960ec4", dependencies = ["base"] : List Text },
{ name = "openchat-bot-sdk", repo = "https://github.com/open-chat-labs/open-chat-bots", version = "v0.2.1", dependencies = ["base", "base64", "ecdsa", "http-types", "http-parser", "itertools", "json", "jwt"] : List Text },
{ name = "ic-websocket-cdk", repo = "https://github.com/omnia-network/ic-websocket-cdk-mo", version = "v0.4.1", dependencies = ["ic-certification", "sha2", "cbor", "base"] : List Text },
{ name = "devefi-jes1-snsneuron", repo = "https://github.com/jesssekeogh/devefi_jes1_snsneuron", version = "v0.1.3", dependencies = ["base", "map", "neuro"] : List Text },
{ name = "devefi-jes1-icpneuron", repo = "https://github.com/jesssekeogh/devefi_jes1_icpneuron", version = "v0.2.3", dependencies = ["base", "neuro", "map"] : List Text },
{ name = "ic", repo = "https://github.com/ZenVoich/ic", version = "640250866d038ac7f8aea0afc82fc96d780d97ae", dependencies = [] : List Text },
{ name = "llm", repo = "https://github.com/dfinity/llm", version = "v0.1.2", dependencies = [] : List Text },
{ name = "rsa", repo = "https://github.com/edjcase/motoko_rsa", version = "2315e05e524a5d1b3c8e4201de16ec681db5a5d9", dependencies = ["base", "new-base", "base-x-encoder", "itertools", "asn1", "sha2", "xtended-numbers"] : List Text },
{ name = "splay", repo = "https://github.com/chenyan2002/motoko-splay", version = "v0.1.0", dependencies = ["base"] : List Text },
{ name = "noise", repo = "https://github.com/jneums/noise", version = "cc25a93d055e01b1f6b64448ad7f64d551e96886", dependencies = ["base"] : List Text },
{ name = "icrc45", repo = "https://github.com/Neutrinomic/icrc45.mo", version = "831c49784dc32eb3103f604a4a288c67b91fcabd", dependencies = ["base", "vector"] : List Text },
{ name = "auction", repo = "https://github.com/research-ag/auction", version = "3.0.0", dependencies = ["base"] : List Text },
{ name = "ed25519", repo = "https://github.com/imsk17/ed25519", version = "0848a4a455f4cd5121ed28ab3a0b76d79344f0a2", dependencies = ["base"] : List Text },
{ name = "bit-map", repo = "https://github.com/NatLabs/BitMap", version = "v0.1.2", dependencies = ["base", "map", "itertools", "augmented-btrees"] : List Text },
{ name = "icrc3-mo", repo = "https://github.com/PanIndustrial-Org/icrc3.mo", version = "v0.3.0", dependencies = ["base", "stable-write-only", "map", "vector", "sha2", "rep-indy-hash", "ic-certification", "class-plus"] : List Text },
{ name = "icrc10-mo", repo = "https://github.com/PanIndustrial-Org/icrc10.mo", version = "v0.0.1", dependencies = ["base", "map"] : List Text },
{ name = "lru-cache", repo = "https://github.com/NatLabs/lru-cache", version = "9782fe76c0ec0a404a9a64c19d9b7dbe96fffa9c", dependencies = ["base", "map", "linked-list"] : List Text },
{ name = "icrc75-mo", repo = "https://github.com/icdevsorg/icrc75.mo", version = "v0.2.0", dependencies = ["map", "map", "vector", "star", "icrc1-mo", "candy", "StableHeapBTreeMap", "ovs-fixed", "timer-tool", "ic-certification", "rep-indy-hash", "class-plus", "base"] : List Text },
{ name = "class-plus", repo = "https://github.com/icdevsorg/class-plus", version = "v0.0.1", dependencies = ["base"] : List Text },
{ name = "assets-api", repo = "https://github.com/vporton/assets_api.mo", version = "v1.0.1", dependencies = [] : List Text },
{ name = "linked-list", repo = "https://github.com/NatLabs/linked-list", version = "1e128c7a1fba63ec32a9673f9fc430fc1aebbece", dependencies = ["base"] : List Text },
{ name = "rbac-motoko", repo = "https://github.com/fury02/rbac-motoko", version = "v0.1.3", dependencies = ["base", "map", "time-consts", "fuzz", "certified-cache", "serde"] : List Text },
{ name = "http-loopback", repo = "https://github.com/bittoko/http-loopback", version = "v0.2.1", dependencies = ["base", "cbor", "map", "rep-indy-hash", "test", "xtended-numbers", "sha2", "utilities", "tecdsa"] : List Text },
{ name = "xtended-random", repo = "https://github.com/edjcase/motoko_random", version = "be6749cfe5c07f37d84b74fb7ed2346730ee3393", dependencies = ["base"] : List Text },
{ name = "memory-hashlist", repo = "https://github.com/fGhost713/Memory-HashList", version = "v2.0.0", dependencies = ["base", "memory-region", "StableTrieMap", "itertools", "test", "memory-buffer", "vector", "fuzz", "bench"] : List Text },
{ name = "certified-assets", repo = "https://github.com/NatLabs/certified-assets", version = "v0.5.1", dependencies = ["base", "ic-certification", "sha2", "http-parser", "http-types", "encoding", "serde", "map", "vector"] : List Text },
{ name = "bitcoin-address-utils", repo = "https://github.com/Universelle-io/bitcoin-address-utils", version = "9d4eaba755660ccf5848c38374291721871ad9d9", dependencies = ["bitcoin", "sha2", "base16"] : List Text },
{ name = "maf", repo = "https://github.com/fury02/async-data-deliveries", version = "30e7a579a599ab8e687e5fe9855f477a6670f9fa", dependencies = ["base", "fuzz", "StableHashMap"] : List Text },
{ name = "mal", repo = "https://github.com/fury02/async-data-deliveries", version = "30e7a579a599ab8e687e5fe9855f477a6670f9fa", dependencies = ["base", "fuzz", "StableHashMap"] : List Text },
{ name = "hmac", repo = "https://github.com/edjCase/motoko_hmac", version = "74deeb9ee34011ed70d19fa264c46959c9077d30", dependencies = ["sha2"] : List Text },
{ name = "cbor", repo = "https://github.com/edjcase/motoko_cbor", version = "v1.0.0", dependencies = ["base", "xtended-numbers"] : List Text },
{ name = "nacdb", repo = "https://github.com/vporton/NacDB", version = "v0.14.3", dependencies = ["base", "stable-rbtree", "stable-buffer", "prng", "StableHeapBTreeMap", "sha2", "cycles-simple", "StableBuffer"] : List Text },
{ name = "web-io", repo = "https://github.com/NatLabs/web-io", version = "v0.0.1", dependencies = ["base", "itertools", "serde", "http", "moh", "parser-combinators", "encoding", "fuzz"] : List Text },
{ name = "base16", repo = "https://github.com/diodechain/motoko_base16", version = "v1.0.0", dependencies = ["base"] : List Text },
{ name = "web-api", repo = "https://github.com/NatLabs/web-io", version = "v0.0.1", dependencies = ["base", "itertools", "serde", "http", "moh", "parser-combinators", "encoding", "fuzz"] : List Text },
{ name = "ovs-fixed", repo = "https://github.com/icdevsorg/ovs-fixed", version = "v0.1.4", dependencies = ["base", "star", "map"] : List Text },
{ name = "simplemath", repo = "https://github.com/sam-thetutor/simpleMath", version = "1c4bd07f007cdc3698fcf6289851e1d13889d9d2", dependencies = ["base"] : List Text },
{ name = "enumeration", repo = "https://github.com/research-ag/enumeration", version = "0.1.1", dependencies = ["base"] : List Text },
{ name = "stable-trie", repo = "https://github.com/research-ag/stable-trie", version = "0.0.1", dependencies = ["base"] : List Text },
{ name = "http-server", repo = "https://github.com/sazalo101/http-server", version = "v1.0.2", dependencies = ["base", "http-server"] : List Text },
{ name = "rep-indy-hash", repo = "https://github.com/skilesare/RepIndyHash.mo", version = "v0.1.1", dependencies = ["base", "vector", "sha2", "encoding", "array", "xtended-numbers"] : List Text },
{ name = "waterway-mops", repo = "https://github.com/jamesbeadle/waterway-mops", version = "98ccbfa61fa3ee583980cd3456c3d41f97efe828", dependencies = ["base"] : List Text },
{ name = "idempotency-keys", repo = "https://github.com/Demali-876/idempotency-keys", version = "83ffffcc4823592784942ed0845a8d1d9532507c", dependencies = ["base"] : List Text },
{ name = "xml", repo = "https://github.com/edjcase/motoko_xml", version = "acb9815b88e835425e24ab64eb19076eec6a3c06", dependencies = ["base", "xtended-numbers", "xtended-text"] : List Text },
{ name = "base", repo = "https://github.com/dfinity/motoko-base", version = "moc-0.14.9", dependencies = [] : List Text },
{ name = "uuid", repo = "https://github.com/aviate-labs/uuid.mo", version = "b88101f0516847727ff45ea54688803c698935e5", dependencies = ["base", "encoding", "io"] : List Text },
{ name = "candid", repo = "https://github.com/edjcase/motoko_candid", version = "2c58aa3665f3cffc0b7083133c80eee32f5517d7", dependencies = ["base", "xtended-numbers"] : List Text },
{ name = "bitcoin", repo = "https://github.com/dfinity/motoko-bitcoin", version = "v0.1.1", dependencies = ["base", "sha2"] : List Text },
{ name = "testpack", repo = "https://github.com/sam-thetutor/mopspackage", version = "8160ee5edf6408141f017d649f46cc48edc43c7e", dependencies = ["base"] : List Text },
{ name = "icrc7-mo", repo = "https://github.com/PanIndustrial-Org/icrc7.mo", version = "v0.5.0", dependencies = ["base", "base", "map", "candy", "StableBuffer", "StableBuffer", "encoding", "vector", "rep-indy-hash", "class-plus"] : List Text },
{ name = "new-base", repo = "https://github.com/dfinity/new-motoko-base", version = "preview-0.4.0", dependencies = [] : List Text },
{ name = "icrc30-mo", repo = "https://github.com/PanIndustrial-Org/icrc30.mo", version = "v0.3.1", dependencies = ["base", "base", "map", "candy", "StableBuffer", "StableBuffer", "encoding", "vector", "rep-indy-hash", "icrc7-mo"] : List Text },
{ name = "icrc37-mo", repo = "https://github.com/PanIndustrial-Org/icrc37.mo", version = "v0.5.1", dependencies = ["base", "base", "map", "candy", "StableBuffer", "StableBuffer", "encoding", "vector", "rep-indy-hash", "icrc7-mo", "map", "class-plus"] : List Text },
{ name = "icrc79-mo", repo = "https://github.com/PanIndustrial-org/icrc79.mo", version = "v0.2.2", dependencies = ["base", "map", "vector", "timer-tool", "star", "StableHeapBTreeMap", "sha2", "candy", "ovs-fixed", "rep-indy-hash"] : List Text },
{ name = "timer-tool", repo = "https://github.com/PanIndustrial-Org/timerTool", version = "v0.1.1", dependencies = ["base", "StableHeapBTreeMap", "star", "map", "ovs-fixed", "class-plus"] : List Text },
{ name = "icrc-nft-mo", repo = "https://github.com/PanIndustrial-Org/icrc_nft.mo", version = "v0.5.0", dependencies = ["base", "base", "map", "candy", "StableBuffer", "StableBuffer", "encoding", "stable-write-only", "ic-certification", "vector", "rep-indy-hash", "icrc3-mo", "icrc37-mo", "icrc7-mo", "class-plus"] : List Text },
{ name = "testpackage", repo = "https://github.com/sam-thetutor/testpackage", version = "ff3fb56c69d2548840df151c2f241897c3d43dd0", dependencies = ["base"] : List Text },
{ name = "xtended-text", repo = "https://github.com/edjcase/motoko_text", version = "c5a2538b71b9a77cb2b22a529a2990dd6142e0d2", dependencies = ["base", "xtended-numbers"] : List Text },
{ name = "stable-rbtree", repo = "https://github.com/canscale/StableRBTree", version = "v0.6.1", dependencies = ["base"] : List Text },
{ name = "principal-ext", repo = "https://github.com/icdevsorg/principal-ext.mo", version = "v0.1.0", dependencies = ["base"] : List Text },
{ name = "incremental-ids", repo = "https://github.com/NatLabs/incremental-ids", version = "68607808489cb7ff63663a392a974e0cb328d1fa", dependencies = ["base", "map"] : List Text },
{ name = "stable-local-log", repo = "https://github.com/PanIndustrial-Org/stable-local-log-mo", version = "v0.1.2", dependencies = ["base", "ovs-fixed", "class-plus", "timer-tool", "star", "map", "icrc10-mo", "vector"] : List Text },
{ name = "ussd-menu-builder", repo = "https://github.com/akimau/motoko-ussd-menu-builder", version = "1c38e6facf425ff77d72998840b3dd9da83993ec", dependencies = ["map", "base", "serde"] : List Text },
{ name = "icrc37-mo-lordrio", repo = "https://github.com/lordrio/icrc37.mo", version = "v0.4.3", dependencies = ["base", "base", "map", "candy", "StableBuffer", "StableBuffer", "encoding", "vector", "rep-indy-hash", "icrc7-mo"] : List Text },
{ name = "icrc72-subscriber-mo", repo = "https://github.com/PanIndustrial-Org/icrc72-subscriber-mo", version = "v0.0.1", dependencies = ["base", "StableHeapBTreeMap", "star", "map", "vector", "ovs-fixed", "candy", "class-plus", "timer-tool"] : List Text },
{ name = "kyc", repo = "https://github.com/ORIGYN_SA/kyc.mo", version = "v0.1.0", dependencies = ["base", "candy", "map", "StableBuffer", "map", "matchers"] : List Text },
{ name = "map", repo = "https://github.com/ZhenyaUsenko/motoko-hash-map", version = "v9.0.1", dependencies = [] : List Text },
{ name = "rxmo", repo = "https://github.com/infu/rxmo", version = "ab65cdca2f286f3f6dbfc3e2c5efc83d80366b6b", dependencies = ["base"] : List Text },
{ name = "star", repo = "https://github.com/icdevs/star.mo", version = "v0.1.1", dependencies = ["base", "matchers"] : List Text },
{ name = "candy", repo = "https://github.com/icdevs/candy_library", version = "v0.3.1", dependencies = ["matchers", "candid", "xtended-numbers", "StableBuffer", "StableBuffer", "map", "map", "candy", "candy", "encoding", "vector", "principal-ext", "base"] : List Text },
{ name = "eddsa", repo = "https://github.com/edjcase/motoko_eddsa", version = "c5d787aa94f82d153a3fdde190e24a58abb6e6ed", dependencies = ["base", "new-base", "base-x-encoder", "asn1", "sha2", "tweetnacl"] : List Text },
{ name = "mosup", repo = "https://github.com/Neutrinomic/mosup", version = "239aa664e7c4e2353b465fb4802ff537d03f4245", dependencies = ["base"] : List Text },
{ name = "candb", repo = "https://github.com/ORIGYN-SA/CanDB", version = "v1.0.8", dependencies = ["base", "StableHashMap", "StableHeapBTreeMap", "array", "encoding", "stable-rbtree", "StableBuffer", "map", "candy", "StableBuffer", "map"] : List Text },
{ name = "devefi", repo = "https://github.com/Neutrinomic/devefi", version = "v0.3.22", dependencies = ["vector", "map", "base", "prng", "account", "itertools", "rechain", "mosup", "devefi-icrc-ledger", "devefi-icp-ledger"] : List Text },
{ name = "rxmodb", repo = "https://github.com/infu/rxmodb", version = "a3b55e054336323477e3608440c6f48cfac5b754", dependencies = ["base", "rxmo", "StableHeapBTreeMap", "vector", "test"] : List Text },
{ name = "json.mo", repo = "https://github.com/aviate-labs/json.mo", version = "v0.1.2", dependencies = ["base", "parser-combinators"] : List Text },
{ name = "evm-txs", repo = "https://github.com/av1ctor/evm-txs.mo", version = "v0.1.3", dependencies = ["base", "rlp", "libsecp256k1", "sha3"] : List Text },
{ name = "itertools", repo = "https://github.com/NatLabs/Itertools", version = "f7d59dfcdff5162828f41af81b5762607806d82b", dependencies = ["base"] : List Text },
{ name = "candy-utils", repo = "https://github.com/ZhenyaUsenko/motoko-candy-utils", version = "v0.7.0", dependencies = ["base", "candy", "StableBuffer", "map"] : List Text },
{ name = "ckbtc-types", repo = "https://github.com/ZenVoich/ckbtc-types", version = "0e73c03e0a4588600773d01463701c53ba0ab145", dependencies = [] : List Text },
{ name = "http-parser", repo = "https://github.com/NatLabs/http-parser.mo", version = "0.3.0", dependencies = ["base", "json.mo", "encoding"] : List Text },
{ name = "libsecp256k1", repo = "https://github.com/av1ctor/libsecp256k1.mo", version = "v0.1.0", dependencies = ["base"] : List Text },
{ name = "canistergeek", repo = "https://github.com/usergeek/canistergeek-ic-motoko", version = "32d1f3a48b1bc12d727b896a69b08bb5f3e5860d", dependencies = ["base"] : List Text },
{ name = "motoko-serde", repo = "https://github.com/NatLabs/serde", version = "v0.1.4", dependencies = ["base", "json", "itertools", "candid", "xtended-numbers", "parser-combinators"] : List Text },
{ name = "chronotrinite", repo = "https://github.com/Neutrinomic/devefi_chronotrinite", version = "7cce392a6f7bffd8171dff32d8ed7e8fb739c205", dependencies = ["base", "StableHeapBTreeMap", "vector", "mosup", "swbstable", "map"] : List Text },
{ name = "certified-http", repo = "https://github.com/infu/certified-http", version = "514314a95ecd5e2afd28dcbba632b33868d62702", dependencies = ["base", "ic-certification", "sha2", "StableHeapBTreeMap"] : List Text },
{ name = "ic-certification", repo = "https://github.com/nomeata/ic-certification", version = "v0.1.3", dependencies = ["sha2", "cbor"] : List Text },
{ name = "candid_stringify", repo = "https://github.com/ORIGYN-SA/candid_stringify", version = "ebaf64b98e9010a4a6a38e520ad5271e3f1b7085", dependencies = ["base", "candid", "itertools", "xtended-numbers"] : List Text },
{ name = "devefi-icp-ledger", repo = "https://github.com/Neutrinomic/devefi_icp_ledger", version = "cca43c11f379d91e31a117d5eeefae17b5244073", dependencies = ["vector", "map", "swb", "StableHeapBTreeMap", "itertools", "base", "mosup"] : List Text },
{ name = "devefi-icrc-sender", repo = "https://github.com/Neutrinomic/devefi_icrc_sender", version = "0b89d790458d041603b5d440396ffaa694b8e8ed", dependencies = ["vector", "StableHeapBTreeMap"] : List Text },
{ name = "devefi-icrc-reader", repo = "https://github.com/Neutrinomic/devefi_icrc_reader", version = "36cc9af5e85714a9d2de3f3859ea266f1f1d5627", dependencies = ["vector"] : List Text },
{ name = "devefi-icrc-ledger", repo = "https://github.com/Neutrinomic/devefi_icrc_ledger", version = "7d5cacb1d3dff31f8e4aadf40f2004ac50d9b592", dependencies = ["vector", "map", "swb", "StableHeapBTreeMap", "base", "mosup"] : List Text },
{ name = "evm-proof-verifier", repo = "https://github.com/horizonx-tech/evm-proof-verifier-motoko", version = "eb7463789813c7879451776d68f93dc3d524595a", dependencies = ["base", "rlp", "sha3", "merkle-patricia-trie"] : List Text },
{ name = "merkle-patricia-trie", repo = "https://github.com/f0i/merkle-patricia-trie.mo", version = "c7829dc9c0577953ad567c910500a7c3aace521e", dependencies = ["base", "rlp", "sha3"] : List Text },
{ name = "motoko-certified-assets", repo = "https://github.com/fermartz/motoko-certified-assets", version = "51f3d373e2bf0fb4b5facf4caa2bacf2efd0bd8d", dependencies = ["base", "ic-certification", "sha2", "StableHeapBTreeMap", "map"] : List Text },
{ name = "stable-write-only", repo = "https://github.com/skilesare/StableWriteOnly.mo", version = "v0.1.0", dependencies = ["base", "vector"] : List Text },
{ name = "StableHeapBTreeMap", repo = "https://github.com/canscale/StableHeapBTreeMap", version = "v0.3.4", dependencies = ["base"] : List Text },
{ name = "sequence", repo = "https://github.com/matthewhammer/motoko-sequence", version = "366c4191d856ed4842267f5ab89d7222ed2d71d0", dependencies = ["base"] : List Text },
{ name = "motoko-sequence", repo = "https://github.com/matthewhammer/motoko-sequence", version = "366c4191d856ed4842267f5ab89d7222ed2d71d0", dependencies = ["base"] : List Text },
{ name = "encoding", repo = "https://github.com/aviate-labs/encoding.mo", version = "overridden", dependencies = ["base", "array"] : List Text },
{ name = "crypto", repo = "https://github.com/aviate-labs/crypto.mo", version = "v0.3.1", dependencies = ["base", "encoding"] : List Text },
{ name = "date.mo", repo = "https://github.com/aviate-labs/date.mo", version = "overridden", dependencies = ["base", "fmt.mo"] : List Text },
{ name = "fmt.mo", repo = "https://github.com/aviate-labs/fmt.mo", version = "v0.1.0", dependencies = ["base"] : List Text },
{ name = "parser-combinators", repo = "https://github.com/aviate-labs/parser-combinators.mo", version = "v0.1.3", dependencies = ["base"] : List Text },
{ name = "io", repo = "https://github.com/aviate-labs/io.mo", version = "overridden", dependencies = ["base"] : List Text },
{ name = "array", repo = "https://github.com/aviate-labs/array.mo", version = "overridden", dependencies = ["base"] : List Text },
{ name = "http", repo = "https://github.com/aviate-labs/http.mo", version = "overridden", dependencies = ["base"] : List Text },
{ name = "testing", repo = "https://github.com/aviate-labs/testing.mo", version = "v0.1.3", dependencies = [] : List Text },
{ name = "StableTrieMap", repo = "https://github.com/NatLabs/StableTrieMap", version = "4781cb03efd34b124c22396c69710b374366c797", dependencies = ["base"] : List Text },
{ name = "StableHashMap", repo = "https://github.com/canscale/StableHashMap", version = "v0.2.2", dependencies = ["base"] : List Text },
{ name = "StableBuffer", repo = "https://github.com/canscale/StableBuffer", version = "v1.3.0", dependencies = ["base"] : List Text },
{ name = "moh", repo = "https://github.com/NatLabs/moh", version = "27f9634adf5b3b85bcf8bfa381875d82395e464c", dependencies = ["base", "encoding", "fmt.mo", "itertools", "xtended-numbers"] : List Text },
{ name = "motoko-datetime", repo = "https://github.com/ByronBecker/motoko-datetime", version = "v0.1.1", dependencies = ["base"] : List Text },
{ name = "rlp", repo = "https://github.com/relaxed04/rlp-motoko", version = "16ee578b1315dd160718f1379a7e20c1f33c7d0d", dependencies = ["base"] : List Text },
{ name = "iterext", repo = "https://github.com/timohanke/motoko-iterext", version = "v2.0.0", dependencies = ["base"] : List Text },
{ name = "json-float", repo = "https://github.com/NatLabs/json.mo", version = "f3c8e7d418a7a8f2d6c0d7e2d276a0a82c2046ff", dependencies = ["base", "parser-combinators"] : List Text },
{ name = "matchers", repo = "https://github.com/kritzcreek/motoko-matchers", version = "v1.3.1", dependencies = ["base"] : List Text },
]